# Generated by Django 5.2.5 on 2025-11-26 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_email_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number using digits, spaces, brackets and an optional leading + sign.', regex='^\\+?[0-9\\s\\-()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_postcode', message='Please enter a valid UK postcode, e.g. SW1A 1AA.', regex='^[A-Z]{1,2}\\d[A-Z\\d]?\\s*\\d[A-Z]{2}$')]),
        ),
    ]
